Initial KeysInUse integration
microsoft/SymCrypt-OpenSSL pull request #74
Opened 2024-02-24 00:36 UTC by mamckee

This PR adds optional KeysInUse logging following the original formatting defined for https://github.com/microsoft/KeysInUse-OpenSSL

- The KeysInUse feature is hidden behind a compile time flag and must be enabled at runtime either by config or environment
- Logging is handled by a dedicated logging thread to minimize overhead on crypto
- All KeysInUse errors are logged to a separate file to avoid polluting the error stack
- Supported private key operations for logging:
    - RSA sign
    - RSA decrypt
    - ECDSA sign

2024-05-23 20:39 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_ecc.c
> +    // pbPublicKeyTmp = *ppbEncodedPublicKey;
NP: this comment does not make much sense with latest code - remove?

2024-05-23 20:40 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_ecc.c
> +    if (!ret)
>!ret [](http://example.com/codeflow?start=8&length=4)

ret != SCOSSL_SUCCESS

2024-05-23 20:44 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_base.c
> +    if (core_get_params != NULL)
>core_get_params != NULL [](http://example.com/codeflow?start=8&length=23)

When does `core_get_params == NULL` here?

Should there be an error condition rather than just starting with KeysInUse disabled?

2024-05-23 21:51 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_base.c
> +                 confMaxFileSize[i] != '\0' && confMaxFileSize[i] < '0' && '9' < confMaxFileSize[i];
>confMaxFileSize[i] < '0' && '9' < confMaxFileSize[i] [](http://example.com/codeflow?start=47&length=52)

This always evaluates to false I think?

I think you may have meant:
`(confMaxFileSize[i] < '0' || '9' < confMaxFileSize[i])`
If we are trimming off the non-numeric prefix?

Feel like we could probably just only allow strings which are immediately numeric and do away with this for loop entirely?

2024-05-23 22:25 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_base.c
> +            p_scossl_keysinuse_set_max_file_size(maxFileSizeBytes);
>maxFileSizeBytes [](http://example.com/codeflow?start=49&length=16)

Should there be a compile time limit on this below the maximum value of off_t?

Should there be an error on overflow (i.e. if `off_t` is 32-bits, and I specify I want max file size to be "4GB", I think this will be set to 0, and no logging will occur?)

2024-05-23 22:30 UTC, samuel-lee-msft commented on SymCryptProvider/symcrypt_prov.cnf
> +logging_delay = 3600
>logging_delay [](http://example.com/codeflow?start=0&length=13)

Maybe this should explicitly have "seconds" in the name?

2024-05-23 22:31 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_base.c
> +            p_scossl_keysinuse_set_max_file_size(maxFileSizeBytes);
>p_scossl_keysinuse_set_max_file_size [](http://example.com/codeflow?start=12&length=36)

We are ignoring return value here? Should we set keysinuseEnabled to false on error?

2024-05-23 22:32 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_base.c
> +            p_scossl_keysinuse_set_logging_delay(atol(confLoggingDelay));
>p_scossl_keysinuse_set_logging_delay [](http://example.com/codeflow?start=12&length=36)

We are ignoring return value here? Should we set keysinuseEnabled to FALSE on error?

2024-05-23 22:36 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_rsa.c
> +    if ((cbEncodedKey = i2d_SymcryptRsaPublicKey(rsaParams, &pbEncodedKey)) < 0)
>i2d_SymcryptRsaPublicKey [](http://example.com/codeflow?start=24&length=24)

Where is this defined?

2024-05-23 22:48 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_rsa.c
> +    if ((cbEncodedKey = i2d_SymcryptRsaPublicKey(rsaParams, &pbEncodedKey)) < 0)
Oh, I see `IMPLEMENT_ASN1_FUNCTIONS_name` above..

I can believe this does the right thing but I don't know how to review this - `IMPLEMENT_ASN1_FUNCTIONS_name` is not documented! :p

Is it not feasible to to call more explicitly supported functions to encode n and e separately and concatenate them appropriately?

2024-05-23 23:15 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +    if (CRYPTO_atomic_add(&keysinuseInfo->refCount, 1, &ref, keysinuseInfo->lock))
`!CRYPTO_atomic_add` here?

2024-05-23 23:15 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +        p_scossl_keysinuse_log_error("p_scossl_keysinuse_upref failed,OPENSSL_%d", ERR_get_error());
>up [](http://example.com/codeflow?start=57&length=2)

down

2024-05-23 23:26 UTC, samuel-lee-msft commented on SymCryptProvider/src/keymgmt/p_scossl_rsa_keymgmt.c
> +    if (keyCtx->keysinuseInfo != NULL &&
check copyCtx is not NULL?

2024-05-23 23:28 UTC, samuel-lee-msft commented
>         (copyCtx->pssRestrictions = OPENSSL_memdup(keyCtx->pssRestrictions, sizeof(SCOSSL_RSA_PSS_RESTRICTIONS))) == NULL)

Probably follow pattern in ecc with jump to cleanup

---
In reply to: [2128187962](https://github.com/microsoft/SymCrypt-OpenSSL/pull/74#issuecomment-2128187962) [](http://example.com/codeflow?ancestors=2128187962)

---
Refers to: SymCryptProvider/src/keymgmt/p_scossl_rsa_keymgmt.c:246 in ca235cd. [](commit_id = ca235cd95e89ee45466ac5e92c0372e06fc483e1, deletion_comment = False)

2024-05-23 23:35 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +            p_scossl_keysinuse_info_free(keysinuseInfo);
>p_scossl_keysinuse_info_free(keysinuseInfo); [](http://example.com/codeflow?start=12&length=44)

I think we leak `keysinuseInfo` here because `keysinuseInfo->refCount` is 0 (not 1)

2024-05-24 21:04 UTC, samuel-lee-msft commented on SymCryptProvider/src/signature/p_scossl_ecdsa_signature.c
> +            keyCtx->keysinuseInfo == NULL)
>keyCtx [](http://example.com/codeflow?start=12&length=6)

Is it definitely true that keyCtxs only contain a single key for their whole lifetime?

It looks like we would have a bunch of memory leaks if a keyCtx is initialized multiple times (i.e. import/generate an already-initialized keyCtx), so I guess this is beyond the scope of KeysInUse.
If we do need to support multiple-initializations of a keyCtx, we need to downref and set keysinuseInfo to NULL at the point of changing the key material the keyCtx contains.

2024-05-24 21:09 UTC, samuel-lee-msft commented on SymCryptProvider/src/signature/p_scossl_ecdsa_signature.c
> +    p_scossl_keysinuse_on_sign(ctx->keyCtx->keysinuseInfo);
>p_scossl_keysinuse_on_sign(ctx->keyCtx->keysinuseInfo); [](http://example.com/codeflow?start=4&length=55)

Probably out of scope for this PR, but it seems like it might be useful to track key usage, along with failure or success - maybe it could indicate some bad key which always fails but is used a lot.

2024-05-24 21:13 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +                keysinuseInfo->refCount++;
>keysinuseInfo->refCount++; [](http://example.com/codeflow?start=16&length=26)

I think this still needs to be an atomic add, right?

Other modifications of refcount are not guarded by the write lock.

2024-05-24 21:15 UTC, mamckee commented on SymCryptProvider/src/p_scossl_base.c
> +    if (core_get_params != NULL)
This is a sanity check, so it should never happen, and it is an error case. We don't want any errors related to keysinuse to interfere with normal provider operation though, so the behavior is the same to the caller with the feature enabled or disabled. This is also why keysinuse errors are logged separately rather than calling ERR_raise.

2024-05-24 21:16 UTC, samuel-lee-msft commented on SymCryptProvider/src/signature/p_scossl_ecdsa_signature.c
> +                keyCtx->keysinuseInfo = p_scossl_keysinuse_info_new(pbPublicKey, cbPublicKey);
>keyCtx->keysinuseInfo = p_scossl_keysinuse_info_new(pbPublicKey, cbPublicKey); [](http://example.com/codeflow?start=16&length=78)

This should probably be a compare-exchange to prevent two threads setting `keyCtx->keysinuseInfo` at the same time and leaking one of them. (Same for RSA)

2024-05-24 21:57 UTC, mamckee commented on SymCryptProvider/src/p_scossl_base.c
> +                 confMaxFileSize[i] != '\0' && confMaxFileSize[i] < '0' && '9' < confMaxFileSize[i];
This was mostly for stripping whitespace, but it looks like OpenSSL already does that for us so that sounds good. We can just check if maxFileSizeBytes <= 0 in p_scossl_keysinuse_set_max_file_size instead of < 0.

2024-05-24 22:06 UTC, mamckee commented on SymCryptProvider/src/p_scossl_base.c
> +            p_scossl_keysinuse_set_max_file_size(maxFileSizeBytes);
p_scossl_keysinuse_set_max_file_size checks for overflow but we don't raise an error for the reason listed above. If this fails we just fall back to the defaults.

2024-05-24 22:11 UTC, mamckee commented on SymCryptProvider/src/p_scossl_base.c
> +            p_scossl_keysinuse_set_max_file_size(maxFileSizeBytes);
We're matching the behavior of the keysinuse engine here. There's two error cases here. Either the max size is too large and we overflow, or the number is negative. In case of overflow, we _could_ have a max size, but falling back to the default is safer. In case of negative it's a misconfiguration and we should ignore as if this was some nonsense value.

2024-05-24 22:13 UTC, mamckee commented on SymCryptProvider/src/p_scossl_base.c
> +            p_scossl_keysinuse_set_max_file_size(maxFileSizeBytes);
I can make this a void return though since we aren't checking.

2024-05-24 22:23 UTC, mamckee commented on SymCryptProvider/src/p_scossl_rsa.c
> +    if ((cbEncodedKey = i2d_SymcryptRsaPublicKey(rsaParams, &pbEncodedKey)) < 0)
It's feasible, but would be alot more code and far less performant :/ The responsibility falls on the providers for this now (same reason why we had to add OSSL_SIGNATURE_PARAM_ALGORITHM_ID to the provider)

The recommended path is to use a provider with the encoder interface to replace i2d_RSAPublicKey, but that would involve exporting the key to the default provider, then using the default provider's encoder. https://www.openssl.org/docs/man3.3/man3/i2d_RSAPublicKey.html.

2024-05-24 22:26 UTC, mamckee commented on SymCryptProvider/src/keymgmt/p_scossl_rsa_keymgmt.c
> +    if (keyCtx->keysinuseInfo != NULL &&
I'll just return NULL in the failure cases above since there's no cleanup.

2024-05-24 22:34 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_base.c
> +            p_scossl_keysinuse_set_max_file_size(maxFileSizeBytes);
`p_scossl_keysinuse_set_max_file_size` will be passed 0 if I write 4GB in the config file and off_t is 32-bits, so there is no ability to check for overflow there, the overflow happens in the parsing in this function.

It would make more logical sense to me to clamp values to some compile-time maximum which fits in an off_t; but it probably doesn't matter a great deal given the config has to be trusted input (just would be nice to make configuring KeysInUse less error-prone)

2024-05-24 22:37 UTC, mamckee commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +            p_scossl_keysinuse_info_free(keysinuseInfo);
Yeah, I'll set refcount at the begining of this block.

2024-05-24 22:47 UTC, mamckee commented on SymCryptProvider/src/signature/p_scossl_ecdsa_signature.c
> +            keyCtx->keysinuseInfo == NULL)
It would be weird for the keyCtx to be used for multiple keys, but not unsupported.

2024-05-24 22:50 UTC, mamckee commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +                keysinuseInfo->refCount++;
We've acquired keysinuseInfo->lock at this point which is used for the refcount operations.

2024-05-24 23:30 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +                keysinuseInfo->refCount++;
https://www.openssl.org/docs/manmaster/man3/CRYPTO_atomic_add.html#:~:text=CRYPTO_atomic_add()%20atomically%20adds,function%20will%20fail.

Atomic add will typically not use the lock

2024-05-24 23:55 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +    PBYTE pbHash = NULL;
>PBYTE pbHash = NULL; [](http://example.com/codeflow?start=4&length=20)

Seems like this may as well be on the stack as:
`BYTE aHash[32] = { 0 };`

2024-05-25 00:05 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +            CRYPTO_THREAD_unlock(sk_keysinuse_info_lock);
>CRYPTO_THREAD_unlock(sk_keysinuse_info_lock); [](http://example.com/codeflow?start=12&length=45)

Hrmm, we might get here having failed to lock `sk_keysinuse_info_lock`, and then incorrectly unlock the lock which another thread has locked.

i.e.
thread A fails to take lock
thread B takes lock
thread A unlocks lock
thread C takes lock
thread B and C corrupt sk_keysinuse_info


Seems like a bug in the OpenSSL documentation :/: [https://www.openssl.org/docs/manmaster/man3/CRYPTO_THREAD_write_lock.html](https://www.openssl.org/docs/manmaster/man3/CRYPTO_THREAD_write_lock.html)

2024-05-28 19:51 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +                keysinuseInfo->refCount++;
Interestingly, I think if CRYPTO_atomic_add did need to take the lock, then it would fail here (as the thread is already locked), so I think the code would need to look something like:

```
INT32 ref = 0;

...

if (!CRYPTO_atomic_add(&keysinuseInfo->refCount, 1, &ref, keysinuseInfo->lock))
{
    // we get here only when atomics not supported on this platform
    // and we failed to take lock because we already own it.
    // simply increment refCount
    keysinuseInfo->refCount++;
}
```

Alternatively, you could have a separate lock specially protecting `keysinuseInfo->refCount`, or not use CRYPTO_atomic_add in up/downref.

2024-05-28 20:13 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +            pthreadErr == EDEADLK) // Already have the lock
>pthreadErr == EDEADLK) // Already have the lock [](http://example.com/codeflow?start=12&length=47)

I don't see how we should ever get this return from `pthread_mutex_lock` here?

2024-05-28 20:24 UTC, samuel-lee-msft commented on SymCryptProvider/src/signature/p_scossl_rsa_signature.c
> +        p_scossl_keysinuse_on_sign(ctx->keyCtx->keysinuseInfo);
>p_scossl_keysinuse_on_sign [](http://example.com/codeflow?start=8&length=26)

Another thing that would be nice is to track what the padding mode was for RSA - would be great to surface PKCS1 usage and try and configure folks to use PSS/OAEP instead.

2024-05-28 20:28 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +                if (keysinuseInfo->firstUse == 0)
>if (keysinuseInfo->firstUse == 0) [](http://example.com/codeflow?start=16&length=33)

Kind of feels like this should be a check of:
```
if ((keysinuseInfo->signCounter + keysinuseInfo->decryptCounter) == 1)
```
and maybe keysinuseInfo->firstUse should be set to now here, rather than in the logging thread sometime later.

2024-05-28 20:44 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +        pthread_mutex_unlock(&logging_thread_mutex);
Actually, here I don't think the signaling thread needs to lock/unlock `logging_thread_mutex` at all - we should be able to call:
```
if ((pthreadErr = pthread_cond_signal(&logging_thread_cond_wake_early)) != 0)
{
    p_scossl_keysinuse_log_error("Failed to signal logging thread,SYS_%d", pthreadErr);
}
```

The mutex is not protecting writing any data here.

2024-05-28 20:49 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +            pthreadErr == EDEADLK) // Already have the lock
>pthreadErr == EDEADLK) // Already have the lock [](http://example.com/codeflow?start=12&length=47)

Why this, we will error out below with pthreadErr != 0 -> Logging thread failed to acquire mutex anyway?

2024-05-28 20:54 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +        }
Should we cleanup / explicitly turn off KeysInUse in these cases, rather than just stopping the logging thread?

2024-05-28 21:28 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +            }
I'm not quite sure I follow this bit.

It seems to be the assumption that the last `first_use_counter` infos are the ones which have just been added to the stack on their first use, but I don't see how this is enforced.
Probably most of the time you will get 1 new info which is first use, and this use will wake the logging thread and the last info on the stack will be the new info.

However, there's nothing stopping another thread with a key which has been used before, but not since the last logging timeout, being pushed on the stack after the new info.

It also looks like if we're on a machine using a new key every 15 minutes, and a logging timeout of 1 hour, that we'll only ever log new keys, and never get around to logging the rest of the stack (at least until we're unloaded)?

Is it prohibitively expensive to just do the dumb thing of logging everything in the stack on first use?

2024-05-28 21:30 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +            now = time(NULL);
>now = time(NULL); [](http://example.com/codeflow?start=12&length=17)

Seems like this should not be in a critical section ideally

2024-05-28 22:14 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_keysinuse.h
> +    UINT decryptCounter;
NP: Any reason these aren't UINT32 / UINT64?

2024-05-28 22:20 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +                pKeysinuseInfo->lastUse = now;
>pKeysinuseInfo->lastUse = now; [](http://example.com/codeflow?start=16&length=30)

It's a little odd to me to set lastUse here, which is more like, lastLogged. There could be a long time between the last call to `p_scossl_keysinuse_add_use` for this info and logging time.

If it's too expensive to get the time in `p_scossl_keysinuse_add_use` (I would expect it shouldn't be relevant compared to cost of asymmetric key operations), then at least should rename the field to lastLogged.

2024-05-28 22:24 UTC, samuel-lee-msft requested changes
I think the overall structure looks good - just many nitpicks.

I have looked at all of the code now and don't have any more comments at the moment. I only skimmed through the interactions with the file system in `p_scossl_keysinuse_log_common`, but I guess that code is unchanged from the engine.

2024-05-31 18:11 UTC, mamckee commented on SymCryptProvider/src/p_scossl_base.c
> +            p_scossl_keysinuse_set_max_file_size(maxFileSizeBytes);
I see, you're right I misunderstood. I agree, it's unlikely anyone will set this file to something so large but clamping to a max value would be the behavior I'd expect as a consumer.

2024-05-31 19:17 UTC, mamckee commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +                keysinuseInfo->refCount++;
I like the first suggestion the best, since we don't have to manage an extra lock, and don't take extra locks on a platform with atomics.

I think the lock shouldn't be passed though. If atomics aren't supported and the lock is NULL, CRYPTO_atomic_add will fail. If the lock is passed, CRYPTO_atomic_add will also try to acquire the lock first. There's potential for deadlock if the implementation changes similar to https://github.com/openssl/openssl/issues/24517.

2024-05-31 19:57 UTC, mamckee commented on SymCryptProvider/src/signature/p_scossl_ecdsa_signature.c
> +                keyCtx->keysinuseInfo = p_scossl_keysinuse_info_new(pbPublicKey, cbPublicKey);
OpenSSL doesn't provide a compatibility layer for compare-exchange atomic functions. I think the only way to do this in a safe, platform-agnostic way is to put this block behind a lock in the keyCtx.

If thread A and B enter this section at the same time, and thread A starts initializing, thread B has to wait for that operation before advancing anyways.

2024-05-31 22:43 UTC, mamckee commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +            pthreadErr == EDEADLK) // Already have the lock
I think I was just trying to be safe when I wrote this. None of the functions that acquire this lock call into each other though so we don't need this check.

2024-05-31 23:04 UTC, mamckee commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +                if (keysinuseInfo->firstUse == 0)
`signCounter` and `decryptCounter` should have been reset before when logged since this is a sliding window.

The names `firstUse` and `lastUse` were carried over from the engine, but they're a bit misleading. I think something like `lastLogTime` and `logTime` would be more accurate.

2024-05-31 23:15 UTC, mamckee commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +        pthread_mutex_unlock(&logging_thread_mutex);
There's a race condition if we don't acquire this lock.

The logging thread acquires `logging_thread_mutex` and performs some initialization before `pthread_cond_timedwait`, which releases the lock. If we signal while the logging thread during this time, the signal is lost and the logging thread won't wake up early.

https://pubs.opengroup.org/onlinepubs/7908799/xsh/pthread_cond_signal.html
> The _pthread_cond_signal()_ and _pthread_cond_broadcast()_ functions have no effect if there are no threads currently blocked on _cond_.

2024-05-31 23:21 UTC, mamckee commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +        }
Probably, the cleanup functions will need to be split into something like `p_scossl_keysinuse_cleanup` that can be called from the logging thread and `p_scossl_keysinuse_teardown` that can be called from the main thread and perform the logging thread join too.

2024-05-31 23:24 UTC, mamckee commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +        }
Actually if we call `p_scossl_keysinuse_cleanup` from the end of the logging thread then `p_scossl_keysinuse_teardown` would just need to join and cleanup the thread

2024-05-31 23:25 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +        pthread_mutex_unlock(&logging_thread_mutex);
I suppose that's true, but I don't see the race as being much different to when the signal is sent just before the logging thread took the mutex for the initialization (i.e. was just processing its last logging).
The signal doesn't do anything unless the logging thread is waiting for the signal.

2024-05-31 23:55 UTC, mamckee commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +            }
It wouldn't be prohibitively expensive and that would simplify so we might as well do that. It doesn't match the behavior of the engine but the important thing is that the usage is logged. It might be a little noisier and fill the log file faster, but it would be less error prone.

2024-05-31 23:57 UTC, mamckee commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +            now = time(NULL);
Probably a bit overkill to have it in the loop as well. The time doens't need to be _that_ precise

2024-05-31 23:58 UTC, mamckee commented on SymCryptProvider/src/p_scossl_keysinuse.h
> +    UINT decryptCounter;
Not really. Might as well make them UINT32.

2024-05-31 23:58 UTC, mamckee commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +                pKeysinuseInfo->lastUse = now;
I'll rename these based on the above comment

2024-06-01 00:05 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +                keysinuseInfo->refCount++;
Nice, yeah, I think I like passing NULL as the lock argument here - make sure reasoning is in a comment.

2024-06-01 00:08 UTC, mamckee commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +        pthread_mutex_unlock(&logging_thread_mutex);
The logging thread checks `first_use_counter` before sleeping, so any first use events that occurred during the last loop are processed before trying to sleep again.

The race would be in these lines, after `first_use_counter` has been checked and the mutex released, but before the thread has gone to sleep:
https://github.com/microsoft/SymCrypt-OpenSSL/blob/ba1d198901745b2df8ec92364d43e16656006c83/SymCryptProvider/src/p_scossl_keysinuse.c#L658-L666

As discussed below, we shouldn't bother with first use count, but `firstUseCounter` currently acts as the predicate for the condition. It should be replaced with a boolean, and we should set it under logging_thread_mutex instead of sk_keysinuse_info_lock.

2024-06-01 00:09 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +                if (keysinuseInfo->firstUse == 0)
Oh, I don't see that `signCounter` / `decryptCounter` are ever reset, my understanding was that they were cumulative across the lifetime of the info object (so would only sum to 0 when the object has just been created with no use yet).

2024-06-04 00:26 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_base.c
> +            p_scossl_keysinuse_set_max_file_size(maxFileSizeBytes);
I see that now on overflow we just keep the default value. That's certainly better than setting the size to 0, but still a little bit unexpected.

I would still probably add a compile time constant in here `SCOSSL_MAX_CONFIGURABLE_FILE_SIZE` and clamp `maxFileSizeBytes` to that.

2024-06-04 00:46 UTC, samuel-lee-msft commented on SymCryptProvider/src/signature/p_scossl_ecdsa_signature.c
> +                keyCtx->keysinuseInfo = p_scossl_keysinuse_info_new(pbPublicKey, cbPublicKey);
Generally prefer to go compare-exchange as we scale up number of threads - but lock should be fine here

2024-06-04 00:56 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +           pthread_mutex_unlock(&logging_thread_mutex);
>pthread_mutex_unlock [](http://example.com/codeflow?start=11&length=20)

NP: indent

2024-06-04 00:58 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +                pKeysinuseInfo->logTime = now;
Seems like:
`lastLogTime` should be named `firstLogTime`, and `logTime` should be named `lastLogTime`?

2024-06-04 01:02 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +            first_use_pending = FALSE;
>first_use_pending = FALSE; [](http://example.com/codeflow?start=12&length=26)

Move this up to be under the `logging_thread_mutex`?

i.e.
```
if (first_use_pending)
{
    first_use_pending = FALSE;
    waitStatus = 0;
}
```

2024-06-04 01:11 UTC, samuel-lee-msft reviewed
Very close to ready - just a few hanging comments

2024-06-04 19:33 UTC, mamckee commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +                pKeysinuseInfo->logTime = now;
Sure, that sounds a little clearer

2024-06-04 19:39 UTC, mamckee commented on SymCryptProvider/src/p_scossl_keysinuse.c
> +            first_use_pending = FALSE;
There's a potential race where the crypto thread has pushed the event to the stack, but hasn't set first_use_pending. In that case the event will be consumed by the logging thread, and first_use_pending will be TRUE at the beginning of the next loop.

That should be fine though, the worst case is that the logging thread makes an extra loop as a no-op.

2024-06-04 21:32 UTC, samuel-lee-msft commented on SymCryptProvider/src/p_scossl_base.c
> +
>maxFileSizeBytes = maxFileSizeBytes * 10 + (confMaxFileSize[i++] - '0'); [](http://example.com/codeflow?start=16&length=72)

Can also overflow here technically - a bit weird to not clamp on this loop too.

2024-06-04 21:40 UTC, samuel-lee-msft submitted a review, later dismissed
Just one nitpick w.r.t. clamping

2024-06-05 18:05 UTC, samuel-lee-msft approved these changes

2024-06-05 19:07 UTC, merged